server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: aurora-mqtt
  redis:
    host: 192.168.2.102
    port: 6379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1ms
        min-idle: 1
      shutdown-timeout: 86400ms
  kafka:
    bootstrap-servers: 139.199.5.205:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

transport:
  mqtt:
    bind_address: 0.0.0.0
    tcp:
      port: 1883
    websocket:
      port: 1884
    # MQTT SSL configuration
    ssl:
      tcp:
        # Enable/disable SSL support
        enabled: true
        port: 8883
      websocket:
        enabled: true
        port: 8884
    netty:
      boss_group_thread_count: ${NETTY_BOSS_GROUP_THREADS:3}
      worker_group_thread_count: ${NETTY_WORKER_GROUP_THREADS:12}
      max_payload_size: ${NETTY_MAX_PAYLOAD_SIZE:65536}
      so_keep_alive: ${NETTY_SO_KEEPALIVE:false}
      soRcvbuf: ${NETTY_SO_RCVBUF:65536}
      soSndbuf: ${NETTY_SO_SNDBUF:65536}
      soBacklog: ${NETTY_SO_BACKLOG:1024}


