server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: aurora-transport
  redis:
    host: 192.168.2.102
    port: 6379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1ms
        min-idle: 1
      shutdown-timeout: 86400ms
  kafka:
    bootstrap-servers: 139.199.5.205:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.chenws.iot.transport.netty.mqtt.bean
  rabbitmq:
    host: 139.199.5.205
    port: 5672
    username: admin
    password: admin
    #支持发布确认
    publisher-confirms: true
    #支持发布返回
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true

transport:
  mqtt:
    bind_address: 0.0.0.0
    tcp:
      port: 1883
    websocket:
      port: 1884
    # MQTT SSL configuration
    ssl:
      tcp:
        # Enable/disable SSL support
        enabled: true
        port: 8883
      websocket:
        enabled: true
        port: 8884
    netty:
      boss_group_thread_count: ${NETTY_BOSS_GROUP_THREADS:3}
      worker_group_thread_count: ${NETTY_WORKER_GROUP_THREADS:12}
      max_payload_size: ${NETTY_MAX_PAYLOAD_SIZE:65536}
      so_keep_alive: ${NETTY_SO_KEEPALIVE:false}
      soRcvbuf: ${NETTY_SO_RCVBUF:65536}
      soSndbuf: ${NETTY_SO_SNDBUF:65536}
      soBacklog: ${NETTY_SO_BACKLOG:1024}


