server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: aurora-transport

transport:
  mqtt:
    # Enable/disable mqtt transport protocol.
    enabled: ${MQTT_ENABLED:true}
    bind_address: ${MQTT_BIND_ADDRESS:0.0.0.0}
    bind_port: ${MQTT_BIND_PORT:1883}
    timeout: ${MQTT_TIMEOUT:10000}
    netty:
      boss_group_thread_count: ${NETTY_BOSS_GROUP_THREADS:1}
      worker_group_thread_count: ${NETTY_WORKER_GROUP_THREADS:12}
      max_payload_size: ${NETTY_MAX_PAYLOAD_SIZE:65536}
      so_keep_alive: ${NETTY_SO_KEEPALIVE:false}
    # MQTT SSL configuration
    ssl:
      # Enable/disable SSL support
      enabled: ${MQTT_SSL_ENABLED:false}
      # SSL protocol: See http://docs.oracle.com/javase/8/docs/technotes/guides/security/StandardNames.html#SSLContext
      protocol: ${MQTT_SSL_PROTOCOL:TLSv1.2}
      # Path to the key store that holds the SSL certificate
      key_store: ${MQTT_SSL_KEY_STORE:mqttserver.jks}
      # Password used to access the key store
      key_store_password: ${MQTT_SSL_KEY_STORE_PASSWORD:server_ks_password}
      # Password used to access the key
      key_password: ${MQTT_SSL_KEY_PASSWORD:server_key_password}
      # Type of the key store
      key_store_type: ${MQTT_SSL_KEY_STORE_TYPE:JKS}


