server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: aurora-analyze
  redis:
    host: 139.199.5.205
    port: 6379
    lettuce:
      pool:
        max-active: 1000
        max-idle: 100
        max-wait: -1ms
        min-idle: 1
      shutdown-timeout: 86400ms
  kafka:
    bootstrap-servers: 139.199.5.205:9092
    consumer:
      group-id: consumer-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: com.chenws.iot.transport.netty.mqtt.bean